name: petevolution
description: A pet evolution app using flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  auto_route: ^7.1.0
  cached_network_image: ^3.2.3
  camera: ^0.10.5+2
  djangoflow_app: ^3.1.0
  djangoflow_app_links: ^1.1.3
  firebase_core: ^2.14.0
  firebase_storage: ^11.2.4
  flex_color_scheme: ^7.1.2
  flutter_bloc: ^8.1.2
  font_awesome_flutter: ^10.5.0
  freezed_annotation: ^2.2.0
  hydrated_bloc: ^9.1.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  progress_builder: ^1.1.3
  responsive_framework: ^1.0.0

dependency_overrides:
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^7.0.0
  build_runner: ^2.4.4
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^2.0.2
  freezed: ^2.3.4
  json_serializable: ^6.7.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat.ttf
          weight: 400
        - asset: assets/fonts/montserrat_bold.ttf
          weight: 700

flutter_gen:
  output: lib/configurations/constants
